import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from "react";
import { PrismaClient } from '@prisma/client'
import moment from 'moment';

export default function Home({ data }) {
  const [events, setevents] = useState([]);


  const eventList = data;


  const fetchEvents = async () => {
    document.getElementsByClassName('results')[0].innerHTML = '';
    document.getElementsByClassName('results')[0].setAttribute('class', 'results');
    
    const boxes = Array.from(document.getElementsByClassName('total'));

    boxes.forEach((box, index) => {
      box.setAttribute('class', 'total hidden');
    });

    var randomEventNumber = Math.floor(Math.random() * eventList.length);


    console.log("Finding event ... " + randomEventNumber);
    var event1 = eventList[Math.floor(randomEventNumber)]; 
    eventList.splice(randomEventNumber, 1);
  
    var event2 = eventList[Math.floor(Math.random() * eventList.length)];

    const carbon1 = await fetch(`/api/carbon/${event1.date}`);
    const carbon2 = await fetch(`/api/carbon/${event2.date}`);

    const carbon1data = await carbon1.json();
    const carbon2data = await carbon2.json();

    const eventModel1 = { date: event1.date, name: event1.name, carbon: carbon1data.carbonTotal, image: event1.image, correct: carbon1data.carbonTotal > carbon2data.carbonTotal };
    const eventModel2 = { date: event2.date, name: event2.name, carbon: carbon2data.carbonTotal, image: event2.image, correct: carbon2data.carbonTotal > carbon1data.carbonTotal};

    const events = [eventModel1, eventModel2];

    setevents(events);
  };

  function reveal(correct) {

    console.log('event[0] ' + events[0].carbon);
    console.log('event[1] ' + events[1].carbon);

    var diff = 0;
    if (events[0].carbon < events[1].carbon)
    {
      diff = 1-  (events[0].carbon / events[1].carbon);
      
    } else {
      diff = 1 - (events[1].carbon / events[0].carbon);
    }

    const percentageDiff = Math.floor(diff * 100);



    const resultsBlock = document.getElementsByClassName('results')[0];

    resultsBlock.innerHTML = correct ? `You win! Energy consumption was ${percentageDiff}% higher on this day for this event` : `You Lose! Energy consumption was ${percentageDiff}% higher on this day for the other event`;

    resultsBlock.setAttribute('class', correct ? 'results green innerbox' : 'results red innerbox');

    const boxes = Array.from(document.getElementsByClassName('hidden'));

    boxes.forEach((box, index) => {
      box.setAttribute('class', 'total');
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the carbon intensity game!
        </h1>

        <p className={styles.description}>
        Carbon intensity is a measure of how clean our electricity is. It refers to how many grams of carbon dioxide (CO<sub>2</sub>) are released to produce a kilowatt hour (kWh) of electricity. 

        Which events do you think had the greatest impact on the total carbon intensity across the day?
        </p>

        <button className="button-53" onClick={fetchEvents}>Click to play!</button>
   
        <div className={styles.grid}>
          { 
          events.map((event) => {
            var counter = 1;
            console.log('yo ' + events[0].carbon);
            counter += 1;
            return (
              <a key={event.date} className={styles.card} onClick={() => reveal(event.correct)}>
                  <h2>{event.name}</h2>
                  <Image src={event.image} width={140} height={100} alt='image of event' />  
                  <p className={"total hidden"}>{event.carbon}<small> gCO<sub>2</sub>/kW over 24 hours</small></p>
              </a>
            );
          })}
        </div>

        <div className="results"></div>
                 
      </main>

      <footer className={styles.footer}>
      <p>This game uses data from the National Grid, Carbon Intensity API 
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          https://api.carbonintensity.org.uk/
        </a>
        </p>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {

  const prisma = new PrismaClient()
  
  const data = await prisma.events.findMany()
  .catch(async (e) => {
      console.error(e)
      await prisma.$disconnect()
      process.exit(1)
  });

  console.log('server' + data[1].eventId)
 
  await prisma.$disconnect();
  return {
      props: { data },
  }
}