import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from "react";
import eventData from '../public/events-data.json';

export default function Home({ data }) {
  const [events, setevents] = useState([]);

  console.log(eventData);
 
  const fetchEvents = async () => {
    var myIndex = Math.floor(Math.random() * eventData.length);
    console.log(myIndex);
    var event1 = eventData[myIndex];
    var event2 = eventData[Math.floor(Math.random() * eventData.length)];
    
console.log(event1);

    const carbon1 = await fetch(`/api/carbon/${event1.date}`);
    const carbon2 = await fetch(`/api/carbon/${event2.date}`);
    const carbon1data = await carbon1.json();
    const carbon2data = await carbon2.json();
    const events = [carbon1data, carbon2data];

    setevents(events);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the carbon intensity game!
        </h1>

        <p className={styles.description}>
          Todays star studded events, who will consume the most energy, what a time to be alive!
          </p>

          <button onClick={fetchEvents}>Get events</button>
     
          {events.map((event) => {
            return (
              <div key={event.requestedDate} className={styles.grid}>
                  <h2>{event.carbonTotal}</h2>
              </div>
            );
          })}
        
                
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
          <Image src="/biscuit.jpg" alt="Mcvities Victoria biscuits" width={140} height={100} />            
          </span>
        </a>
      </footer>
    </div>
  );
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const data = "HELLO";

  // Pass data to the page via props
  return { props: { data } }
}